server {
    listen 80;
    listen [::]:80;
    server_name nulleonauth.tech www.nulleonauth.tech;

    root /var/www/nulleonauth.tech/current;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "public, max-age=300";
    }

    location ~* \.(?:css|js|webp|png|svg|woff2)$ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
