server {
    listen 80;
    listen [::]:80;
    server_name nulleonauth.tech www.nulleonauth.tech;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/nulleonauth.tech/current;
    }
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name nulleonauth.tech www.nulleonauth.tech;

    root /var/www/nulleonauth.tech/current;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/nulleonauth.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nulleonauth.tech/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "public, max-age=300";
    }

    location ~* \.(?:css|js|webp|png|svg|woff2)$ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
