[package]
name = "nulleon-authenticator"
version = "0.2.7"
description = "Nulleon Authenticator Backend"
authors = ["nulleon"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "nulleon-authenticator"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.10.2", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
argon2 = "0.5"
aes-gcm = "0.10"
rand = "0.8"
base64 = "0.21"
bip39 = "2.0"
sha2 = "0.10"
xcap = "0.9.8"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp"] }
rqrr = "0.11"
url = "2.5"
percent-encoding = "2"
tauri-plugin-clipboard-manager = "=2.3.2"

dirs = "6"
tempfile = "3"
zeroize = "1"

[dev-dependencies]
qrcode = { version = "0.14", default-features = false }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
